export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

export const ADD_CATEGORY = "ADD_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY"
export const CLEAR_CURRENT_CATEGORY = "CLEAR_CURRENT_CATEGORY"

export const ADD_RECORD = "ADD_RECORD"
export const EDIT_RECORD = "EDIT_RECORD"
export const DELETE_RECORD = "EDIT_RECORD"
export const SET_CURRENT_RECORD = "SET_CURRENT_RECORD"
export const CLEAR_CURRENT_RECORD = "CLEAR_CURRENT_RECORD"